### PR TITLE
Fix for invalid author URL

### PR DESCRIPTION
**Pull request by j05u3**
This error was generating misbehavior and impossibility to add the extension to new projects.

### CODE REVIEW

**Comment by j05u3** [comment]
https://github.com/robertodevs/zeplin-flutter-extended/issues/8

**Comment by j05u3** [comment]
Sorry for committing that last commit to this PR, it was a fix for the problem that when design is like this:
image
Flutter code used to output this:
image

I mean horizontal gradient instead of vertical gradient.

**Comment by j05u3** [comment]
@robertodevs thanks for merging it, hope to be able to use soon

**Comment by robertodevs** [comment]
Ready bro, I publish the extension to Zeplin, is just waiting for been approved. Thanks for your contribution. I was wondering if you want to help me with some improvements I am working for the extension. This is about the integration of Components and Screens from Zeplin. Let me know and send me a DM if you are interested.

**Comment by robertodevs** [comment]
published*

**Comment by j05u3** [comment]
> Ready bro, I publish the extension to Zeplin, is just waiting for been approved. Thanks for your contribution. I was wondering if you want to help me with some improvements I am working for the extension. This is about the integration of Components and Screens from Zeplin. Let me know and send me a DM if you are interested.

I am interested, I couldn't find your email so I DM'd you through instagram

**Pull request merged**
